-- MySQL Script generated by MySQL Workbench
-- Sat Jan 30 22:12:38 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SistemaTickets
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SistemaTickets` ;

-- -----------------------------------------------------
-- Schema SistemaTickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaTickets` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `SistemaTickets` ;

-- -----------------------------------------------------
-- Table `SistemaTickets`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Rol` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreRol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idRol`)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`idRol` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`TipoDocumento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`TipoDocumento` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`TipoDocumento` (
  `idTipoDocumento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreDocumento` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idTipoDocumento`)  COMMENT '',
  UNIQUE INDEX `UNIQUE_TD` (`idTipoDocumento` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `numDocumento` VARCHAR(15) NULL COMMENT '',
  `nombreCompleto` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `idRolPrincipal` INT NOT NULL COMMENT '',
  `usuario` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `idTipoDocumento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`idUsuario` ASC)  COMMENT '',
  INDEX `fk_u_rol` (`idRolPrincipal` ASC)  COMMENT '',
  INDEX `fk_u_tipodocumento` (`idTipoDocumento` ASC)  COMMENT '',
  CONSTRAINT `fk_u_rol`
    FOREIGN KEY (`idRolPrincipal`)
    REFERENCES `SistemaTickets`.`Rol` (`idRol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_u_tipodocumento`
    FOREIGN KEY (`idTipoDocumento`)
    REFERENCES `SistemaTickets`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`Proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Proyecto` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nomProyecto` VARCHAR(255) NULL COMMENT '',
  `objProyecto` VARCHAR(255) NULL COMMENT '',
  `inicioProyecto` DATETIME NULL COMMENT '',
  `finProyecto` DATETIME NULL COMMENT '',
  `productivoProyecto` TINYINT(1) NULL COMMENT '',
  `idLider` INT NOT NULL COMMENT '',
  UNIQUE INDEX `UNIQUE` (`idProyecto` ASC)  COMMENT '',
  PRIMARY KEY (`idProyecto`, `idLider`)  COMMENT '',
  INDEX `fk_p_usuario` (`idLider` ASC)  COMMENT '',
  CONSTRAINT `fk_p_usuario`
    FOREIGN KEY (`idLider`)
    REFERENCES `SistemaTickets`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`TipoItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`TipoItem` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`TipoItem` (
  `idProyecto` INT NOT NULL COMMENT '',
  `idTipoItem` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(255) NULL COMMENT '',
  INDEX `fk_ti_proyecto` (`idProyecto` ASC)  COMMENT '',
  PRIMARY KEY (`idTipoItem`)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`idTipoItem` ASC)  COMMENT '',
  CONSTRAINT `fk_ti_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `SistemaTickets`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Estado` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Estado` (
  `idTipoItem` INT NOT NULL COMMENT '',
  `idEstado` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombreEstado` VARCHAR(255) NULL COMMENT '',
  `tipoEstado` CHAR(1) NULL COMMENT '',
  INDEX `fk_e_tipoitem` (`idTipoItem` ASC)  COMMENT '',
  PRIMARY KEY (`idEstado`)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`idEstado` ASC)  COMMENT '',
  CONSTRAINT `fk_e_tipoitem`
    FOREIGN KEY (`idTipoItem`)
    REFERENCES `SistemaTickets`.`TipoItem` (`idTipoItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Equipo` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idProyecto` INT NOT NULL COMMENT '',
  `nombreEquipo` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`idEquipo`)  COMMENT '',
  INDEX `fk_e_proyecto` (`idProyecto` ASC)  COMMENT '',
  CONSTRAINT `fk_e_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `SistemaTickets`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`UsuarioRolEquipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`UsuarioRolEquipo` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`UsuarioRolEquipo` (
  `idUsuarioRolEquipo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idEquipo` INT NOT NULL COMMENT '',
  `idUsuario` INT NOT NULL COMMENT '',
  `idRol` INT NOT NULL COMMENT '',
  `esLider` TINYINT(1) NULL COMMENT '',
  `activo` TINYINT(1) NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`idUsuarioRolEquipo`)  COMMENT '',
  INDEX `fk_ure_usuario` (`idUsuario` ASC)  COMMENT '',
  INDEX `fk_ure_equipo` (`idEquipo` ASC)  COMMENT '',
  INDEX `fk_ure_rol` (`idRol` ASC)  COMMENT '',
  CONSTRAINT `fk_ure_equipo`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `SistemaTickets`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ure_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `SistemaTickets`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ure_rol`
    FOREIGN KEY (`idRol`)
    REFERENCES `SistemaTickets`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Item` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Item` (
  `idProyecto` INT NOT NULL COMMENT '',
  `idItem` INT NOT NULL COMMENT '',
  `tituloItem` VARCHAR(255) NOT NULL COMMENT '',
  `descItem` VARCHAR(255) NULL COMMENT '',
  `fechacreacion` DATETIME NULL COMMENT '',
  `idTipoItem` INT NOT NULL COMMENT '',
  `prioridad` VARCHAR(45) NULL COMMENT '',
  `estadoActual` INT NOT NULL COMMENT '',
  `responsable` INT NOT NULL COMMENT '',
  INDEX `fk_i_proyecto` (`idProyecto` ASC)  COMMENT '',
  PRIMARY KEY (`idItem`)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`idItem` ASC)  COMMENT '',
  INDEX `fk_i_tipoitem` (`idTipoItem` ASC)  COMMENT '',
  INDEX `fk_i_estado` (`estadoActual` ASC)  COMMENT '',
  INDEX `fk_i_usuariorolequipo` (`responsable` ASC)  COMMENT '',
  CONSTRAINT `fk_i_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `SistemaTickets`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_i_tipoitem`
    FOREIGN KEY (`idTipoItem`)
    REFERENCES `SistemaTickets`.`TipoItem` (`idTipoItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_i_estado`
    FOREIGN KEY (`estadoActual`)
    REFERENCES `SistemaTickets`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_i_usuariorolequipo`
    FOREIGN KEY (`responsable`)
    REFERENCES `SistemaTickets`.`UsuarioRolEquipo` (`idUsuarioRolEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`WorkFlow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`WorkFlow` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`WorkFlow` (
  `idWorkFlow` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idEstadoActual` INT NOT NULL COMMENT '',
  `idEstadoSiguiente` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idWorkFlow`)  COMMENT '',
  INDEX `fk_wf_estadoactual` (`idEstadoSiguiente` ASC)  COMMENT '',
  INDEX `fk_wf_estadosiguiente` (`idEstadoActual` ASC)  COMMENT '',
  UNIQUE INDEX `idWorkFlow_UNIQUE` (`idWorkFlow` ASC)  COMMENT '',
  CONSTRAINT `fk_wf_estadoactual`
    FOREIGN KEY (`idEstadoActual`)
    REFERENCES `SistemaTickets`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wf_estadosiguiente`
    FOREIGN KEY (`idEstadoSiguiente`)
    REFERENCES `SistemaTickets`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`TransicionItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`TransicionItem` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`TransicionItem` (
  `idTransicionItem` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idItem` INT NOT NULL COMMENT '',
  `idWorkFlow` INT NOT NULL COMMENT '',
  `actor` INT NOT NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  `comentario` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`idTransicionItem`)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`idTransicionItem` ASC)  COMMENT '',
  INDEX `fk_ti_item` (`idItem` ASC)  COMMENT '',
  INDEX `fk_ti_usuario` (`actor` ASC)  COMMENT '',
  INDEX `fk_ti_workflow` (`idWorkFlow` ASC)  COMMENT '',
  CONSTRAINT `fk_ti_item`
    FOREIGN KEY (`idItem`)
    REFERENCES `SistemaTickets`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ti_usuario`
    FOREIGN KEY (`actor`)
    REFERENCES `SistemaTickets`.`UsuarioRolEquipo` (`idUsuarioRolEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ti_workflow`
    FOREIGN KEY (`idWorkFlow`)
    REFERENCES `SistemaTickets`.`WorkFlow` (`idWorkFlow`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`EquipoAtencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`EquipoAtencion` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`EquipoAtencion` (
  `idEquipoAtencion` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idEquipo` INT NOT NULL COMMENT '',
  `idEstado` INT NOT NULL COMMENT '',
  INDEX `fk_ea_estado` (`idEstado` ASC)  COMMENT '',
  INDEX `fk_ea_equipo` (`idEquipo` ASC)  COMMENT '',
  PRIMARY KEY (`idEquipoAtencion`)  COMMENT '',
  UNIQUE INDEX `UNIQUE` (`idEquipoAtencion` ASC)  COMMENT '',
  CONSTRAINT `fk_ea_estado`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `SistemaTickets`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ea_equipo`
    FOREIGN KEY (`idEstado`)
    REFERENCES `SistemaTickets`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
