-- MySQL Script generated by MySQL Workbench
-- Sat Jan 23 18:39:34 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SistemaTickets
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SistemaTickets` ;

-- -----------------------------------------------------
-- Schema SistemaTickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaTickets` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `SistemaTickets` ;

-- -----------------------------------------------------
-- Table `SistemaTickets`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Rol` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Rol` (
  `idRol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `UNIQUE` (`idRol` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`TipoDocumento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`TipoDocumento` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`TipoDocumento` (
  `idTipoDocumento` INT NOT NULL AUTO_INCREMENT,
  `nombreDocumento` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoDocumento`),
  UNIQUE INDEX `UNIQUE` (`idTipoDocumento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `numDocumento` VARCHAR(15) NULL,
  `nombreCompleto` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `idRolPrincipal` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `idTipoDocumento` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idRolPrincipal`),
  UNIQUE INDEX `UNIQUE` (`idUsuario` ASC),
  INDEX `fk_rol` (`idRolPrincipal` ASC),
  INDEX `fk_tipodocumento` (`idTipoDocumento` ASC),
  CONSTRAINT `fk_rol`
    FOREIGN KEY (`idRolPrincipal`)
    REFERENCES `SistemaTickets`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipodocumento`
    FOREIGN KEY (`idTipoDocumento`)
    REFERENCES `SistemaTickets`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`Proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Proyecto` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `nomProyecto` VARCHAR(255) NULL,
  `objProyecto` VARCHAR(255) NULL,
  `inicioProyecto` DATETIME NULL,
  `finProyecto` DATETIME NULL,
  `productivoProyecto` TINYINT(1) NULL,
  `idLider` INT NOT NULL,
  UNIQUE INDEX `UNIQUE` (`idProyecto` ASC),
  PRIMARY KEY (`idProyecto`, `idLider`),
  INDEX `fk_usuario` (`idLider` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`idLider`)
    REFERENCES `SistemaTickets`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`TipoItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`TipoItem` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`TipoItem` (
  `idProyecto` INT NOT NULL,
  `idTipoItem` INT NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  INDEX `fk_proyecto` (`idProyecto` ASC),
  PRIMARY KEY (`idTipoItem`, `idProyecto`),
  UNIQUE INDEX `UNIQUE` (`idTipoItem` ASC),
  CONSTRAINT `fk_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `SistemaTickets`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Estado` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Estado` (
  `idTipoItem` INT NOT NULL,
  `idEstado` INT NOT NULL,
  `nombreEstado` VARCHAR(255) NULL,
  `tipoEstado` CHAR(1) NULL,
  INDEX `fk_tipoitem` (`idTipoItem` ASC),
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `UNIQUE` (`idEstado` ASC),
  CONSTRAINT `fk_tipoitem`
    FOREIGN KEY (`idTipoItem`)
    REFERENCES `SistemaTickets`.`TipoItem` (`idTipoItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Equipo` (
  `idEquipo` INT NOT NULL,
  `idProyecto` INT NOT NULL,
  `nombreEquipo` VARCHAR(255) NULL,
  PRIMARY KEY (`idEquipo`, `idProyecto`),
  INDEX `fk_proyecto` (`idProyecto` ASC),
  CONSTRAINT `fk_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `SistemaTickets`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`UsuarioRolEquipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`UsuarioRolEquipo` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`UsuarioRolEquipo` (
  `idUsuarioRolEquipo` INT NOT NULL AUTO_INCREMENT,
  `idEquipo` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idRol` INT NOT NULL,
  `esLider` TINYINT(1) NULL,
  `activo` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idUsuarioRolEquipo`),
  INDEX `fk_usuario` (`idUsuario` ASC),
  INDEX `fk_equipo` (`idEquipo` ASC),
  INDEX `fk_rol` (`idRol` ASC),
  CONSTRAINT `fk_equipo`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `SistemaTickets`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `SistemaTickets`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol`
    FOREIGN KEY (`idRol`)
    REFERENCES `SistemaTickets`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`Item` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`Item` (
  `idProyecto` INT NOT NULL,
  `idItem` INT NOT NULL,
  `tituloItem` VARCHAR(255) NOT NULL,
  `descItem` VARCHAR(255) NULL,
  `fechacreacion` DATETIME NULL,
  `idTipoItem` INT NOT NULL,
  `prioridad` VARCHAR(45) NULL,
  `estadoActual` INT NOT NULL,
  `responsable` INT NOT NULL,
  INDEX `fk_proyecto` (`idProyecto` ASC),
  PRIMARY KEY (`idItem`),
  UNIQUE INDEX `UNIQUE` (`idItem` ASC),
  INDEX `fk_tipoitem` (`idTipoItem` ASC),
  INDEX `fk_estado` (`estadoActual` ASC),
  INDEX `fk_usuariorolequipo` (`responsable` ASC),
  CONSTRAINT `fk_proyecto`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `SistemaTickets`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipoitem`
    FOREIGN KEY (`idTipoItem`)
    REFERENCES `SistemaTickets`.`TipoItem` (`idTipoItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estado`
    FOREIGN KEY (`estadoActual`)
    REFERENCES `SistemaTickets`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuariorolequipo`
    FOREIGN KEY (`responsable`)
    REFERENCES `SistemaTickets`.`UsuarioRolEquipo` (`idUsuarioRolEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`WorkFlow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`WorkFlow` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`WorkFlow` (
  `idWorkFlow` INT NOT NULL AUTO_INCREMENT,
  `idEstadoActual` INT NOT NULL,
  `idEstadoSiguiente` INT NOT NULL,
  PRIMARY KEY (`idWorkFlow`),
  INDEX `fk_estadoactual` (`idEstadoSiguiente` ASC),
  INDEX `fk_estadosiguiente` (`idEstadoActual` ASC),
  UNIQUE INDEX `UNIQUE` (`idWorkFlow` ASC),
  CONSTRAINT `fk_estadoactual`
    FOREIGN KEY (`idEstadoActual`)
    REFERENCES `SistemaTickets`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estadosiguiente`
    FOREIGN KEY (`idEstadoSiguiente`)
    REFERENCES `SistemaTickets`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`TransicionItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`TransicionItem` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`TransicionItem` (
  `idTransicionItem` INT NOT NULL AUTO_INCREMENT,
  `idItem` INT NOT NULL,
  `idWorkFlow` INT NOT NULL,
  `actor` INT NOT NULL,
  `fecha` DATETIME NULL,
  `comentario` VARCHAR(255) NULL,
  PRIMARY KEY (`idTransicionItem`),
  UNIQUE INDEX `UNIQUE` (`idTransicionItem` ASC),
  INDEX `fk_item` (`idItem` ASC),
  INDEX `fk_usuario` (`actor` ASC),
  INDEX `fk_workflow` (`idWorkFlow` ASC),
  CONSTRAINT `fk_item`
    FOREIGN KEY (`idItem`)
    REFERENCES `SistemaTickets`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`actor`)
    REFERENCES `SistemaTickets`.`UsuarioRolEquipo` (`idUsuarioRolEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workflow`
    FOREIGN KEY (`idWorkFlow`)
    REFERENCES `SistemaTickets`.`WorkFlow` (`idWorkFlow`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTickets`.`EquipoAtencion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SistemaTickets`.`EquipoAtencion` ;

CREATE TABLE IF NOT EXISTS `SistemaTickets`.`EquipoAtencion` (
  `idEquipoAtencion` INT NOT NULL AUTO_INCREMENT,
  `idEquipo` INT NOT NULL,
  `idEstado` INT NOT NULL,
  INDEX `fk_estado` (`idEstado` ASC),
  INDEX `fk_equipo` (`idEquipo` ASC),
  PRIMARY KEY (`idEquipoAtencion`),
  UNIQUE INDEX `UNIQUE` (`idEquipoAtencion` ASC),
  CONSTRAINT `fk_estado`
    FOREIGN KEY (`idEquipo`)
    REFERENCES `SistemaTickets`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo`
    FOREIGN KEY (`idEstado`)
    REFERENCES `SistemaTickets`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
